// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/aalia-homepage/V1.tsx": () => import("../components/mockups/aalia-homepage/V1.tsx"),
  "./components/mockups/aalia-homepage/V2.tsx": () => import("../components/mockups/aalia-homepage/V2.tsx"),
  "./components/mockups/aalia-homepage/V3.tsx": () => import("../components/mockups/aalia-homepage/V3.tsx"),
  "./components/mockups/aalia-homepage/V4.tsx": () => import("../components/mockups/aalia-homepage/V4.tsx"),
  "./components/mockups/aalia-homepage/VariationA.tsx": () => import("../components/mockups/aalia-homepage/VariationA.tsx"),
  "./components/mockups/aalia-homepage/VariationB.tsx": () => import("../components/mockups/aalia-homepage/VariationB.tsx")
};
