// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/aalia-homepage/VariationA.tsx": () => import("../components/mockups/aalia-homepage/VariationA.tsx"),
  "./components/mockups/aalia-homepage/VariationB.tsx": () => import("../components/mockups/aalia-homepage/VariationB.tsx")
};
